[package]
name = "octopus-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octopus-common = {version = "*", path = "../octopus-common"}
octopus-web = {version = "*", path = "../octopus-web"}
